# Theory/Computation Problems

### Problem 1 (20 points) 
Show that the stationary point (zero gradient) of the function
$$
\begin{aligned}
    f=2x_{1}^{2} - 4x_1 x_2+ 1.5x^{2}_{2}+ x_2
\end{aligned}
$$
is a saddle (with indefinite Hessian). Find the directions of downslopes away from the saddle. Hint: Use Taylor's expansion at the saddle point. Find directions that reduce $f$.

### Problem 2 (50 points) 

* (10 points) Find the point in the plane $x_1+2x_2+3x_3=1$ in $\mathbb{R}^3$ that is nearest to the point $(-1,0,1)^T$. Is this a convex problem? Hint: Convert the problem into an unconstrained problem using $x_1+2x_2+3x_3=1$.

* (40 points) Implement the gradient descent and Newton's algorithm for solving the problem. Attach your codes along with a short summary including (1) the initial points tested, (2) corresponding solutions, (3) a log-linear convergence plot.

### Problem 3 (10 points) 
Let $f(x)$ and $g(x)$ be two convex functions defined on the convex set $\mathcal{X}$. 
* (5 points) Prove that $af(x)+bg(x)$ is convex for $a>0$ and $b>0$. 
* (5 points) In what conditions will $f(g(x))$ be convex?

### Problem 4 (bonus 10 points)
Show that $f({\bf x}_1) \geq f(\textbf{x}_0) + 
    \textbf{g}_{\textbf{x}_0}^T(\textbf{x}_1-\textbf{x}_0)$ for a convex function $f(\textbf{x}): \mathcal{X} \rightarrow \mathbb{R}$ and for $\textbf{x}_0$, $\textbf{x}_1 \in \mathcal{X}$. 

    
# Design Problems

### Problem 5 (20 points) 
Consider an illumination problem: There are $n$ lamps and $m$ mirrors fixed to the ground. The target reflection intensity level is $I_t$. The actual reflection intensity level on the $k$th mirror can be computed as $\textbf{a}_k^T \textbf{p}$, where $\textbf{a}_k$ is given by the distances between all lamps to the mirror, and $\textbf{p}:=[p_1,...,p_n]^T$ are the power output of the lamps. The objective is to keep the actual intensity levels as close to the target as possible by tuning the power output $\textbf{p}$.

* (5 points) Formulate this problem as an optimization problem. 
* (5 points) Is your problem convex?
* (5 points) If we require the overall power output of any of the $n$ lamps to be less than $p^*$, will the problem have a unique solution?
* (5 points) If we require no more than half of the lamps to be switched on, will the problem have a unique solution?

---

# Solutions

### Problem 1 solution

Find a stationary point

$$
                \begin{aligned}
                    &\frac{\partial f}{\partial x_1} = 4x_1-4x_2=0\\
                    &\frac{\partial f}{\partial x_2} = -4x_1+3x_2+1=0
                \end{aligned}
$$

Solve these to get the stationary point $x_* = [1,1]^T$.

Calculate the Hessian to get $H=[4, -4; -4, 3]$. It is indefinite since one eigenvalue is positive and the other is negative. So the stationary point is a saddle point.
        
To find the direction of downslope, denote $\partial \textbf{x}_*=\textbf{x}-\textbf{x}_*$ and $\partial f_* = f(\textbf{x})-f(\textbf{x}_*)$: 

$$
            \begin{aligned}
                \partial f_* & = \nabla f_* \partial \textbf{x}_* + \frac{1}{2} \partial \textbf{x}_*^T \textbf{H} \partial\textbf{x}_* \\
                & = \frac{1}{2}(2\partial x_1 -\partial x_2)(2\partial x_1 -3\partial x_2)
            \end{aligned}
$$

Set $\partial f_*<0$ to get the downslopes $2\partial x_1 -\partial x_2<0$ and $2\partial x_1 -3\partial x_2>0$ or $2\partial x_1 -\partial x_2>0$ and $2\partial x_1 -3\partial x_2<0$.

### Problem 2 solution

Solve the following problem
$$
            \begin{aligned}
                \min_{x_1,x_2,x_3} & \quad (x_1+1)^2+x_2^2 + (x_3-1)^2 \\
                \text{subject to:} & \quad x_1+2x_2+3x_3=1 
            \end{aligned}
$$
Substituting $x_1=1-2x_2-3x_3$, the problem reduces to an unconstrained optimization problem. The solution is $x_1=-15/14,x_2=-1/7,x_3=11/14$.

The unconstrained problem has positive definite Hessian everywhere. The problem is thus convex. You can also show that the original problem has a convex objective function and a convex feasible solution set.

In [101]:
# Sample code for gradient descent

import numpy as np
obj = lambda x: (2 - 2*x[0] - 3*x[1])**2 + x[0]**2 + (x[1]-1)**2# note that this is 1D. In Prob 2 it should be 2D.
def grad(x):
     return np.array([10*x[0] + 12*x[1] - 8, 20*x[1] + 12*x[0] -14])
eps = 1e-3  # termination criterion
x0= np.array([0,0])  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps
x = soln[k]  # start with the initial guess
error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 0.01  # set a fixed step size to start with

# Armijo line search
def line_search(x, d):
    a = 1.  # initialize step size
    
    def phi(a,x,d):
        return obj(x)+a*0.8*np.dot(grad(x),d)

    while phi(a,x,d)<obj(x+a*d):  # while phi(a,x)<obj(x-a*grad(x)): # if f(x+a*d)>phi(a) then backtrack. d is the search direction
        a = 0.5*a
        
    return a

while error >= eps:  # keep searching while gradient norm is larger than eps
    d = -grad(x)
    
    a = line_search(x, d)
    
    x = x+a*d
    soln.append(x)
    error = np.linalg.norm(grad(x))
#     error
soln  # print the search trajectory

[array([0, 0]),
 array([0.0625  , 0.109375]),
 array([0.10986328, 0.19580078]),
 array([0.14542389, 0.26428223]),
 array([0.17178619, 0.31872964]),
 array([0.19098449, 0.36219818]),
 array([0.20460775, 0.39707492]),
 array([0.21389699, 0.42522498]),
 array([0.2257459 , 0.47098649]),
 array([0.22716314, 0.50022586]),
 array([0.22287655, 0.52006219]),
 array([0.20820431, 0.54894461]),
 array([0.124532  , 0.61427662]),
 array([0.08599204, 0.62803184]),
 array([0.03645422, 0.67896418]),
 array([0.02045071, 0.67844123]),
 array([-0.02277453,  0.70166208]),
 array([-0.03478701,  0.71666537]),
 array([-0.05054416,  0.72192391]),
 array([-0.06039699,  0.73242714]),
 array([-0.08354146,  0.74195478]),
 array([-0.0856678 ,  0.74706109]),
 array([-0.09917469,  0.75791006]),
 array([-0.10562305,  0.7599035 ]),
 array([-0.10953627,  0.76424141]),
 array([-0.11897805,  0.76794228]),
 array([-0.11977577,  0.77009513]),
 array([-0.12519875,  0.77452096]),
 array([-0.12784025,  0.77526882]),
 array([-0

### Problem 3 solution

For any two points $x_1$ and $x_2$, we have 

$$
            f(\lambda x_1 + (1-\lambda)x_2) \leq \lambda f(x_1) + (1-\lambda) f(x_2)
$$
and 
$$
            g(\lambda x_1 + (1-\lambda)x_2) \leq \lambda g(x_1) + (1-\lambda) g(x_2).
$$
Then 
$$
            \begin{aligned}
            & af(\lambda x_1 + (1-\lambda)x_2)+bg(\lambda x_1 + (1-\lambda)x_2) \\  
            & \leq a(\lambda f(x_1) + (1-\lambda) f(x_2)) + b(\lambda g(x_1) + (1-\lambda) g(x_2))\\
            & = \lambda (af(x_1)+bg(x_1)) + (1-\lambda)(af(x_2)+bg(x_2)).
            \end{aligned}
$$
Therefore by definition $af(x)+bg(x)$ is convex. 

The second-order derivative is $f''(g')^2+g''f'$. If $f''(g')^2+g''f'>0$ then $f(g)$ is convex. One special case will be when $f$ is monotonically increasing, i.e., $f'>0$.

### Problem 4 solution

The following is a proof for a 1D case. 

#### Necessity: 

If $f$ is convex, we have
$$
        f(x + \lambda(y-x)) \leq (1-\lambda)f(x)+\lambda f(y),
$$
    for $\lambda \in [0,1]$. Divide both sides by $\lambda$ to have:
$$
        f(y) \geq f(x) + \frac{f(x + \lambda(y-x))-f(x)}{\lambda}.
$$
	Take $t \rightarrow 0$ to get $f(y) \geq f(x) + 
    f'(x)(y-x)$.
    
#### Sufficiency: 

Let $z = \lambda x + (1-\lambda)y$ for $\lambda \in [0,1]$. We have
    $f(x) \geq f(z) + f'(z)(x-z)$, $f(y) \geq f(z) + f'(z)(y-z)$. Multiplying the first inequality by $\lambda$, the second by $1-\lambda$, add the two together to have
    $\lambda f(x) + (1-\lambda) f(y) \geq f(z)$. Thus $f$ is convex.
    
For a general case in $\mathbb{R}^n$, please see Page 70 ``Proof of first-order convexity condition'' in *Convex Optimization* by Stephen Boyd.

### Problem 5 solution


The problem can be formulated as
$$
\begin{aligned}
\min_{\textbf{p}} \quad & \sum_{k=1}^m \left(\textbf{a}_k^T \textbf{p} - I_t\right)^2\\
\text{s.t.} \quad & 0 \leq p_i \leq p_{max} ~\forall i=1,...,n
\end{aligned}
$$

The Hessian of the objective function is

$$
H = 2\sum_{k=1}^m \textbf{a}_k \textbf{a}_k^T
$$

The problem has a convex feasible domain since constraints are simple bounds.

$H$ is positive semi-definite when $\{\textbf{a}_k\}_{k=1}^m$ does not span $\mathbb{R}^n$, in which case the problem is convex but not strictly convex, or otherwise $H$ is positive defininte, in which case the problem is strictly convex.

Adding the constraint $\sum_{k=1}^n p_i \leq p^*$ does not change the convexity of the feasible domain, since this constraint is linear in $\textbf{p}$.

Adding the constraint $\sum_{k=1}^n \mathbb{1}(p_i > 0) \leq n/2$, where $\mathbb{1}(condition)$ returns 1 if condition is true or otherwise 0, makes the feasible domain non-convex. To see this, consider the case with two lamps ($n=2$). $(p_1, p_2)=(1,0)$ and $(p_1,p_2)=(0,1)$ are feasible (one lamp on and the other off). But $(p_1,p_2)=(0.5, 0.5)$, which is along the line segment between $(1,0)$ and $(0,1)$, is not since both lamps are on in this case.