# Theory/Computation Problems

### Problem 1 (20 points) 
Show that the stationary point (zero gradient) of the function
$$
\begin{aligned}
    f=2x_{1}^{2} - 4x_1 x_2+ 1.5x^{2}_{2}+ x_2
\end{aligned}
$$
is a saddle (with indefinite Hessian). Find the directions of downslopes away from the saddle. Hint: Use Taylor's expansion at the saddle point. Find directions that reduce $f$.

### Problem 2 (50 points) 

* (10 points) Find the point in the plane $x_1+2x_2+3x_3=1$ in $\mathbb{R}^3$ that is nearest to the point $(-1,0,1)^T$. Is this a convex problem? Hint: Convert the problem into an unconstrained problem using $x_1+2x_2+3x_3=1$.

* (40 points) Implement the gradient descent and Newton's algorithm for solving the problem. Attach your codes along with a short summary including (1) the initial points tested, (2) corresponding solutions, (3) a log-linear convergence plot.

### Problem 3 (10 points) 
Let $f(x)$ and $g(x)$ be two convex functions defined on the convex set $\mathcal{X}$. 
* (5 points) Prove that $af(x)+bg(x)$ is convex for $a>0$ and $b>0$. 
* (5 points) In what conditions will $f(g(x))$ be convex?

### Problem 4 (bonus 10 points)
Show that $f({\bf x}_1) \geq f(\textbf{x}_0) + 
    \textbf{g}_{\textbf{x}_0}^T(\textbf{x}_1-\textbf{x}_0)$ for a convex function $f(\textbf{x}): \mathcal{X} \rightarrow \mathbb{R}$ and for $\textbf{x}_0$, $\textbf{x}_1 \in \mathcal{X}$. 

# Design Problems

### Problem 5 (20 points) 
Consider an illumination problem: There are $n$ lamps and $m$ mirrors fixed to the ground. The target reflection intensity level is $I_t$. The actual reflection intensity level on the $k$th mirror can be computed as $\textbf{a}_k^T \textbf{p}$, where $\textbf{a}_k$ is given by the distances between all lamps to the mirror, and $\textbf{p}:=[p_1,...,p_n]^T$ are the power output of the lamps. The objective is to keep the actual intensity levels as close to the target as possible by tuning the power output $\textbf{p}$.

* (5 points) Formulate this problem as an optimization problem. 
* (5 points) Is your problem convex?
* (5 points) If we require the overall power output of any of the $n$ lamps to be less than $p^*$, will the problem have a unique solution?
* (5 points) If we require no more than half of the lamps to be switched on, will the problem have a unique solution?

# Note

For this homework, you may want to attach sketches as means to explain your ideas. Here is how you can attach images.

![everly1](img/everly7.jpg)

![HW2P1](img/HW2P1.jpg)

![HW2P2](img/HW2P2.jpg)

In [16]:
# sample code for Problem 2
import numpy as np
from matplotlib import pyplot as plt

# x[0] corresponds to x2 and x[1] with x3
obj = lambda x: (5*x[0]**2-8*x[0]+12*x[0]*x[1]+10*x[1]**2-14*x[1]+5)
def grad(x):
    return [10*x[0]-8+12*x[1], 12*x[0]+20*x[1]-14] #x[0] corresponds to x2 and x[1] corresponds to x3


eps = 1e-3  # termination criterion
x0 = [0., 0.]  # initial guess
k = 0  # counter
soln = [x0]  # use an array to store the search steps
x = soln[k]  # start with the initial guess

error = np.linalg.norm(grad(x))  # compute the error. Note you will need to compute the norm for 2D grads, rather than the absolute value
a = 0.01  # set a fixed step size to start with

# Armijo line search
# def line_search(x):
#     a = 1.  # initialize step size
#     phi = lambda a, x: obj(x) - a*0.8*grad(x)**2  # define phi as a search criterion
#     while phi(a,x)<obj(x-a*grad(x)):  # if f(x+a*d)>phi(a) then backtrack. d is the search direction
#         a = 0.5*a
#     return a

while error >= eps:  # keep searching while gradient norm is larger than eps
#     a = line_search(x)
    x = np.array(x) - a*np.array(grad(x))
    soln.append(x)
    error = np.linalg.norm(grad(x))
soln  # print the search trajectory


[[0.0, 0.0],
 array([0.08, 0.14]),
 array([0.1352, 0.2424]),
 array([0.172592, 0.317696]),
 array([0.19720928, 0.37344576]),
 array([0.21267486, 0.41509149]),
 array([0.2215964 , 0.44655221]),
 array([0.22585049, 0.4706502 ]),
 array([0.22678742, 0.4894181 ]),
 array([0.2253785 , 0.50431999]),
 array([0.22232225, 0.51641057]),
 array([0.21812076, 0.52644979]),
 array([0.21313471, 0.53498534]),
 array([0.207623  , 0.54241211]),
 array([0.20177124, 0.54901493]),
 array([0.19571233, 0.55499939]),
 array([0.18954117, 0.56051403]),
 array([0.18332537, 0.56566629]),
 array([0.17711288, 0.57053398]),
 array([0.17093751, 0.57517364]),
 array([0.16482292, 0.57962641]),
 array([0.15878546, 0.58392238]),
 array([0.15283623, 0.58808365]),
 array([0.14698257, 0.59212657]),
 array([0.14122912, 0.59606335]),
 array([0.13557861, 0.59990318]),
 array([0.13003237, 0.60365311]),
 array([0.12459076, 0.60731861]),
 array([0.11925345, 0.610904  ]),
 array([0.11401962, 0.61441278]),
 array([0.10888813, 0.617

![HW2P3](img/HW2P3.jpg)

![HW2P4](img/HW2P4.jpg)

![HW2P5](img/HW2P5.jpg)